import io.netty.channel.PendingBytesTracker.DefaultChannelPipelinePendingBytesTracker;
public class FunctionUse21216 {
public void funcUse() {
DefaultChannelPipelinePendingBytesTracker defaultchannelpipelinependingbytestracker = new DefaultChannelPipelinePendingBytesTracker();
defaultchannelpipelinependingbytestracker.decrementPendingOutboundBytes(null);
}
}